spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photoshoot_project_management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail: #for gmail smtp see manual: https://www.baeldung.com/spring-email
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  liquibase:
    change-log: classpath:*db/change-log.xml

project:
  picture:
    upload:
      directory: D:\\graduation-project\\photoshoot-project-management\\uploadDirectory

logging:
  level:
    root: info
    am.itspace: debug
  file:
    name: D:\\graduation-project\\photoshoot-project-management\\logs\\application-%d{yyyy-MM-dd-HH-mm-ss}.%i.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
