spring:
  datasource:
    url:
    username:
    password:
  mail: #for gmail smtp see manual: https://www.baeldung.com/spring-email
    host: smtp.mail.ru
    port: 465
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  jpa:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  liquibase:
    change-log:

project:
  picture:
    upload:
      directory:

server:
  url:
  port: 8081

logging:
  level:
    root: info
    am.itspace: debug
  file:
    name:
  logback:
    rollingpolicy:
      max-file-size:
